#!/usr/bin/env python
# -*- coding: utf-8 -*-

DEFAULT_SIZE = "14"

font_list = [
    ["Anonymous Pro", {'size': DEFAULT_SIZE, 'filename': 'anonymous-pro'}],
    ["Aurulent Sans Mono", {'size': DEFAULT_SIZE, 'filename': 'aurulent-sans-mono'}],
    ["AverageMono", {'size': DEFAULT_SIZE, 'filename': 'average-mono'}],
    ["Bitstream Vera Sans Mono", {'size': DEFAULT_SIZE, 'filename': 'bitstream-vera-sans-mono'}],
    ["BPmono", {'size': DEFAULT_SIZE, 'filename': 'bp-mono'}],
    ["Bront", {'size': DEFAULT_SIZE, 'filename': 'bront'}],
    ["CamingoCode", {'size': DEFAULT_SIZE, 'filename': 'camingo-code'}],
    ["CMU Typewriter Text", {'size': DEFAULT_SIZE, 'filename': 'cmu-typewriter'}],
    ["Code New Roman", {'size': DEFAULT_SIZE, 'filename': 'code-new-roman'}],
    ["CodingFontTobi", {'size': '16', 'filename': 'coding-font-tobi'}],
    ["Consola Mono", {'size': DEFAULT_SIZE, 'filename': 'consola-mono'}],
    ["Courier Prime Code", {'size': DEFAULT_SIZE, 'filename': 'courierprime-code'}],
    ["Cousine", {'size': DEFAULT_SIZE, 'filename': 'cousine'}],
    ["CPMono_v07", {'size': DEFAULT_SIZE, 'filename': 'cp-mono'}],
    ["Crisp", {'size': DEFAULT_SIZE, 'filename': 'crisp'}],
    ["Cutive Mono", {'size': DEFAULT_SIZE, 'filename': 'cutive-mono'}],
    ["DejaVu Sans Mono", {'size': DEFAULT_SIZE, 'filename': 'dejavu-sans-mono'}],
    ["Dina ttf 10px", {'size': '10', 'filename': 'dina'}],
    ["Droid Sans Mono", {'size': DEFAULT_SIZE, 'filename': 'droid-sans-mono'}],
    ["Edlo", {'size': DEFAULT_SIZE, 'filename': 'edlo'}],
    ["Fantasque Sans Mono", {'size': DEFAULT_SIZE, 'filename': 'fantasque-sans-mono'}],
    ["Fira Code", {'size': DEFAULT_SIZE, 'filename': 'fira-code'}],
    ["Fira Mono", {'size': DEFAULT_SIZE, 'filename': 'fira-mono'}],
    ["Fixedsys Excelsior 3.01", {'size': DEFAULT_SIZE, 'filename': 'fixed-sys-excelsior'}],
    ["FreeMono", {'size': DEFAULT_SIZE, 'filename': 'free-mono'}],
    ["GohuFont", {'size': DEFAULT_SIZE, 'filename': 'gohufont'}],
    ["Hack", {'size': DEFAULT_SIZE, 'filename': 'hack'}],
    ["Hasklig", {'size': DEFAULT_SIZE, 'filename': 'hasklig'}],
    ["Hermit", {'size': DEFAULT_SIZE, 'filename': 'hermit'}],
    ["Inconsolata", {'size': DEFAULT_SIZE}, 'filename': 'inconsolata'],
    ["Iosevka", {'size': DEFAULT_SIZE, 'filename': 'iosevka'}],
    ["Latin Modern Mono Light 10", {'size': DEFAULT_SIZE, 'filename': 'latin-modern-mono'}],
    ["Lekton", {'size': DEFAULT_SIZE, 'filename': 'lekton'}],
    ["Liberation Mono", {'size': DEFAULT_SIZE, 'filename': 'liberation-mono'}],
    ["Linux Libertine Mono", {'size': DEFAULT_SIZE, 'filename': 'linux-libertine-mono'}],
    ["Luculent", {'size': DEFAULT_SIZE, 'filename': 'luculent'}],
    ["Luxi Mono", {'size': DEFAULT_SIZE, 'filename': 'luxi-mono'}],
    ["Mensch", {'size': DEFAULT_SIZE, 'filename': 'mensch'}],
    ["Meslo LG M DZ", {'size': DEFAULT_SIZE, 'filename': 'meslo'}],
    ["Metrickal", {'size': DEFAULT_SIZE, 'filename': 'metrickal'}],
    ["monoOne", {'size': DEFAULT_SIZE, 'filename': 'mono-one'}],
    ["MonoSpatial", {'size': DEFAULT_SIZE, 'filename': 'mono-spatial'}],
]
